#velvet_fingers:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  
  
  # Effort Position Controllers ---------------------------------------
  velvet_fingers_joint_1_effort_pos_controller:
    type: effort_controllers/JointPositionController
    joint: velvet_fingers_joint_1
    pid: {p: 100.0, i: 1, d: 1, i_clamp_min: -1000, i_clamp_max: 1000}

  # Forward Position Controllers ---------------------------------------
  velvet_fingers_joint_1_forward_pos_controller:
    type: position_controllers/JointPositionController
    joint: velvet_fingers_joint_1

  # Forward Velocity Controllers ---------------------------------------
  velvet_fingers_joint_1_forward_vel_controller:
    type: velocity_controllers/JointVelocityController
    joint: velvet_fingers_joint_1








