  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  
  
  # Group Velocity Controllers ---------------------------------------
  apple_group_forward_vel_controller:
    type: velocity_controllers/JointGroupVelocityController
#    type: velocity_controllers/JointVelocityController
    joints:
      - lbr_iiwa_joint_1
      - lbr_iiwa_joint_2
      - lbr_iiwa_joint_3
      - lbr_iiwa_joint_4
      - lbr_iiwa_joint_5
      - lbr_iiwa_joint_6
      - lbr_iiwa_joint_7
      - velvet_fingers_joint_1

  # HQP Velocity Controller ----------------------------------------
  apple_hqp_vel_controller:
    type: hqp_controllers/HQPVelocityController
    joints:
      - lbr_iiwa_joint_1
      - lbr_iiwa_joint_2
      - lbr_iiwa_joint_3
      - lbr_iiwa_joint_4
      - lbr_iiwa_joint_5
      - lbr_iiwa_joint_6
      - lbr_iiwa_joint_7
#      - velvet_fingers_joint_1






